### ISSUE TITLE
Build for Android using Unity(Internal, not gradle), when running on android, it says NoClassDefFoundError.

### ISSUE THREAD

**Issue by cdytoby** [facebook/facebook-sdk-for-unity#131]
```

12-19 11:33:22.819 E/Unity   (25368): AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookActivity;
12-19 11:33:22.819 E/Unity   (25368): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookActivity;
12-19 11:33:22.819 E/Unity   (25368): 	at com.facebook.internal.Validate.hasFacebookActivity(Validate.java:216)
12-19 11:33:22.819 E/Unity   (25368): 	at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:265)
12-19 11:33:22.819 E/Unity   (25368): 	at com.facebook.unity.FB.Init(FB.java:86)
12-19 11:33:22.819 E/Unity   (25368): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
12-19 11:33:22.819 E/Unity   (25368): 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
12-19 11:33:22.819 E/Unity   (25368): 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
12-19 11:33:22.819 E/Unity   (25368): 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-19 11:33:22.819 E/Unity   (25368): 	at android.os.Looper.loop(Looper.java:154)
12-19 11:33:22.819 E/Unity   (25368): 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
12-19 11:33:22.819 E/Unity   (25368): Caused by: java.lang.ClassNotFoundException: com.facebook.FacebookActivity
12-19 11:33:22.819 E/Unity   (25368): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
12-19 11:33:22.819 E/Unity   (25368): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
12-19 11:33:22.819 E/Unity   (25368): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
12-19 11:33:22.819 E/Unity   (25368): 	at java.lang.ClassLoader.loadClass(ClassLoader.j
```

Unity 2017.2.0f3, Facebook SDK for Unity 7.10.1

**Comment by cdytoby** [comment]
If using android library 26 or more after updating google library resolver, this issue will happen. 

Reverse Android Library to previous version by copying from other project, it works.

That means, if I use multiple plugin, and library resolver overwrite from one plugin to another, this issue will possibly happen.
