### ISSUE TITLE
Native Ad error en Android

### ISSUE THREAD

**Issue by nicolaslorusso** [facebook/facebook-sdk-for-unity#136]
Hello, i've implemented Audience Network in a project which is using Unity 2017.2.0. I'm also building with proguard.
I've added native ads which are working fine on editor but when i make a build for android i get an exception like this every time i want to display one:
`AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='registerExternalLogReceiver' signature='(Ljava/lang/String;)V' in class Lcom.facebook.ads.NativeAd;
	java.lang.NoSuchMethodError: no non-static method with name='registerExternalLogReceiver' signature='(Ljava/lang/String;)V' in class Lcom.facebook.ads.NativeAd;
	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:49)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:164)
	at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
	at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
	at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
	...`

**Comment by nicolaslorusso** [comment]
Well i finally solved the issue. The problem was that i was missing a rule in custom proguard-user.txt (if you use a custom proguard file). Proguard was stripping the private method NativeAd.registerExternalLogReceiver which is probably not referenced in java but its used via unity lib in NativeAd.cs.
I added this rule in proguard:
`-keep class com.facebook.ads.** { *; }`
