### ISSUE TITLE
Can't build with facebook-unity-sdk-7.13.0

### ISSUE THREAD

**Issue by yasuohasegawa** [facebook/facebook-sdk-for-unity#176]
Hi, I'm trying to add newest facebook SDK to my project, but I did not make build success. It's taking a couple of days. I fixed a couple of issues such as Multidex issue.  Also, I can't build a ".apk" in Unity even I changed the build system to internal. It doesn't work at all, but the only things I can do is export Android Project file.
<br>
I'm running on Unity 2017.3.0f3 on a MacBook Air Sierra 10.12.6
It's an app with several plugins :
-FB SDK
-OpenCV
-GoogleAnalytics

**From the exported Android Project file,  I got the following error:**

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:74)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:115)
	at com.android.apkzlib.zip.StoredEntry.read(StoredEntry.java:327)
	at com.android.apkzlib.sign.SignatureExtension.setDigestForEntry(SignatureExtension.java:496)
	at com.android.apkzlib.sign.SignatureExtension.added(SignatureExtension.java:484)
	at com.android.apkzlib.sign.SignatureExtension.access$100(SignatureExtension.java:97)
	at com.android.apkzlib.sign.SignatureExtension$1.lambda$added$1(SignatureExtension.java:311)
	at com.android.apkzlib.sign.SignatureExtension$1$$Lambda$362/1955733384.run(Unknown Source)
	at com.android.apkzlib.zip.ZFile.notify(ZFile.java:2023)
	at com.android.apkzlib.zip.ZFile.addToEntries(ZFile.java:1674)
	at com.android.apkzlib.zip.ZFile.processAllReadyEntries(ZFile.java:1615)
	at com.android.apkzlib.zip.ZFile.add(ZFile.java:1572)
	at com.android.apkzlib.zip.ZFile.add(ZFile.java:1553)
	at com.android.apkzlib.zfile.ApkZFileCreator.writeFile(ApkZFileCreator.java:141)
	at com.android.builder.internal.packaging.IncrementalPackager.updateFiles(IncrementalPackager.java:172)
	at com.android.builder.internal.packaging.IncrementalPackager.updateAssets(IncrementalPackager.java:231)
	at com.android.build.gradle.tasks.PackageAndroidArtifact.doTask(PackageAndroidArtifact.java:553)
	at com.android.build.gradle.tasks.PackageAndroidArtifact.doFullTaskAction(PackageAndroidArtifact.java:360)
	at com.android.build.gradle.tasks.PackageApplication.doFullTaskAction(PackageApplication.java:56)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
<br>
<br>

**My "Build.gradle" is:**
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:2.3.0'
	}
}

allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
   }
}

apply plugin: 'com.android.application'

dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'cameraplugin-release', ext:'aar')
	compile(name: 'com.android.support.animated-vector-drawable-25.3.1', ext:'aar')
	compile(name: 'com.android.support.appcompat-v7-25.3.1', ext:'aar')
	compile(name: 'com.android.support.cardview-v7-25.3.1', ext:'aar')
	compile(name: 'com.android.support.customtabs-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-compat-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-core-ui-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-core-utils-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-fragment-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-media-compat-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-v4-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-vector-drawable-25.3.1', ext:'aar')
	compile(name: 'facebook-android-wrapper-7.12.1', ext:'aar')
	compile(name: 'facebook-applinks', ext:'aar')
	compile(name: 'facebook-common', ext:'aar')
	compile(name: 'facebook-core', ext:'aar')
	compile(name: 'facebook-login', ext:'aar')
	compile(name: 'facebook-messenger', ext:'aar')
	compile(name: 'facebook-places', ext:'aar')
	compile(name: 'facebook-share', ext:'aar')
	compile 'com.android.support:multidex:1.0.1'
}

android {
	compileSdkVersion 27
	buildToolsVersion '27.0.3'

	defaultConfig {
		minSdkVersion 21
		targetSdkVersion 27
		applicationId 'xx.xx.xx'
		multiDexEnabled true
	}

	dexOptions {
		javaMaxHeapSize "4g"
	}

	lintOptions {
		abortOnError false
	}

	aaptOptions {
		noCompress '.unity3d', '.ress', '.resource', '.obb','bin/data/119e64b2680dc45e78dfe6bcfd17e4de.resource','bin/data/1915cec10840248268bcaeb9ff456118.resource','bin/data/19e69ca3d43a04c949b1168c7bcdc0e2.resource','bin/data/1b3ee61ae9a7f4b5ea153f71ef18b624.resource','bin/data/28d2b5485b9e74a69b6f11e67a881bd1.resource','bin/data/2d1a051de8c0f41de8319ccb14d7c925.resource','bin/data/70814ceeb34b34074978e5e3f254ff30.resource','bin/data/75b1e0db08b2a4f4abb29f8312fcd2e2.resource','bin/data/8dc7c709203164f968bfcd1d0797acba.resource','bin/data/cb77cc94747a542318560dd2cb944c60.resource','bin/data/cccfad642c35d45aaa00538039dbf4d3.resource','bin/data/da6a186e6c5a446c18feaf72ba32f81e.resource','bin/data/dd33f4a1556654fb2b551867c6eec659.resource','bin/data/sharedassets0.resource'
	}

	buildTypes {
  		debug {
 			minifyEnabled false
 			useProguard false
 			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'
  			jniDebuggable true
  		}
  		release {
 			minifyEnabled false
 			useProguard false
  			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'
  			signingConfig signingConfigs.debug
  		}
	}

}

<br>
<br>

I did increase the maximum heap size for the Gradle daemon to 4608 MB in project "Gradle.properties",  and clean project and build, but it didn't work.

When I google about FaceBook SDK for Unity build issue, everyone seems to have the same kind of trouble. 
Any information I'll appreciate.

**Comment by TeamSidGames** [comment]
Resolution for Dex issues on adding Google Play Services 0.95 and Facebook sdk 7.13.0 plugins to Unity 2018.2.0f2

Step 1: First import GooglePlayServices0.95 plugin from this link https://github.com/playgameservices/play-games-plugin-for-unity.

Step 2: Un Check PlayServicesResolver folder when showed folder structure to import.

Step 3: Now Import Facebook SDK 7.13.0 unity package from https://developers.facebook.com/docs/unity/downloads/

Step 4: Here import all folders of the facebook sdk plugin.

Step 5: Now select Assets/PlayServicesResolver/VersionHandler/Update

Step 6: Now select Assets/PlayServicesResolver/AndroidResolver/Resolve

Step 7: Now select Assets/PlayServicesResolver/AndroidResolver/Settings and then uncheck Enable Auto-Resolution

Step 8: Now go to Project Panel and go to Assets/Plugins/Android/ and delete all folders except folder with this name "com.google.games.gpgs-plugin-support-0.9.50"

Step 9: Now go to Project Panel and go to Assets/Plugins/Android/ and delete the following files

com.android.support.animated-vector-drawable-25.3.1
com.android.support.customtabs-25.3.1
com.android.support.support-annotations-25.3.1
com.android.support.support-v4-25.3.1
com.android.support.support-vector-drawable-25.3.1

Now proceed with build making. It should work. :)

**Comment by yasuohasegawa** [comment]
Thank you for the solution. I have to work with Unity 2017.3.0f3, and I did your solution with Unity 2017.3.0f3. I haven't got to build success, but I already talked to my client about this, and we gave up.
Thank you for your time, sir!!!

**Comment by shohan4556** [comment]
unable to solve the problem

**Comment by ohadbroide** [comment]
Does not work for me :{
