### ISSUE TITLE
App Crash on Android 4.4

### ISSUE THREAD

**Issue by trpzn** [facebook/facebook-sdk-for-unity#219]
Tested my app on 3 devices Android version 7, 8 & 4.4.
Only on kitkat(4.4) app crash in milliseconds.
This is the error log on android.
Using SDK 7.15.1 and Unity3D 2018.2.0f2

```
E/AndroidRuntime( 6497): FATAL EXCEPTION: main
E/AndroidRuntime( 6497): Process: com.mycompany.mygame, PID: 6497
E/AndroidRuntime( 6497): java.lang.NoClassDefFoundError: android.support.v4.content.LocalBroadcastManager
E/AndroidRuntime( 6497):        at com.facebook.internal.BoltsMeasurementEventListener.open(BoltsMeasurementEventListener.java:54)
E/AndroidRuntime( 6497):        at com.facebook.internal.BoltsMeasurementEventListener.getInstance(BoltsMeasurementEventListener.java:70)
E/AndroidRuntime( 6497):        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:313)
E/AndroidRuntime( 6497):        at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:42)
E/AndroidRuntime( 6497):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1616)
E/AndroidRuntime( 6497):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1587)
E/AndroidRuntime( 6497):        at android.app.ActivityThread.installProvider(ActivityThread.java:5193)
E/AndroidRuntime( 6497):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4788)
E/AndroidRuntime( 6497):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
E/AndroidRuntime( 6497):        at android.app.ActivityThread.access$1500(ActivityThread.java:166)
E/AndroidRuntime( 6497):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
E/AndroidRuntime( 6497):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6497):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6497):        at android.app.ActivityThread.main(ActivityThread.java:5584)
E/AndroidRuntime( 6497):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6497):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6497):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
E/AndroidRuntime( 6497):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
E/AndroidRuntime( 6497):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  581): Activity destroy timeout for ActivityRecord{4291f7f0 u0 com.mycompany.mygame/com.unity3d.player.UnityPlayerActivity t12 f}
```

**Comment by trpzn** [comment]
An update:
The error only happens in apk compilation on windows (using my pc and unity cloud build), but don't have error if you compile the apk on Mac.

**Comment by studentutu** [comment]
@trpzn similar issue in #237

**Comment by KylinChang** [comment]
There is a similar discussion in Firebase:
https://github.com/firebase/quickstart-unity/issues/402
https://github.com/googlesamples/unity-jar-resolver/issues/241

We will upgrade resolver to 1.2.119 to fix the issue

**Comment by swats1010** [comment]
Hi , 
I upgraded my resolver to 1.2.144 and made that jetifier changes also to try to resolve the issue but nothing seems working for me .
