### ISSUE TITLE
IAP broken in 7.15.1 - Unable to resume activity {com.package.name/com.unity.purchasing.googleplay.PurchaseActivity}: java.lang.RuntimeException: Window couldn't find content container view

### ISSUE THREAD

**Issue by zenith-jacob** [facebook/facebook-sdk-for-unity#245]
So, steps to reproduce:

- Unity 2018.2
- IAP
- Facebook SDK 7.15.1
- Firebase Analytics, Crashlytics
- Onesignal SDK
- No ads etc.

You're not able to make a purchase or log-in to Facebook - the app crashes with the following error:

>  E AndroidRuntime: FATAL EXCEPTION: main
>  E AndroidRuntime: Process: com.Zenith.Cartoon, PID: 19894
>  E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
>  E AndroidRuntime: Unity version     : 2018.2.9f1
>  E AndroidRuntime: Device model      : samsung SM-N910C
>  E AndroidRuntime: Device fingerprint: samsung/treltexx/trelte:6.0.1/MMB29K/N910CXXS2DRI2:user/release-keys
>  E AndroidRuntime: 
>  E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to resume activity {com.HIDDEN.HIDDEN/com.unity.purchasing.googleplay.PurchaseActivity}: java.lang.RuntimeException: Window couldn't find content container view
>  E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4155)
>  E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4246)
>  E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3360)
>  E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
>  E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
>  E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
>  E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
>  E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7225)
>  E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
>  E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>  E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
>  E AndroidRuntime: Caused by: java.lang.RuntimeException: Window couldn't find content container view
>  E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4614)
>  E AndroidRuntime: 	at com.android.internal.policy.MultiPhoneWindow.generateLayout(MultiPhoneWindow.java:1141)
>  E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4683)
>  E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2263)
>  E AndroidRuntime: 	at com.facebook.marketing.internal.ButtonIndexer.processViews(Unknown Source)
>  E AndroidRuntime: 	at com.facebook.marketing.internal.ButtonIndexer.startTracking(Unknown Source)
>  E AndroidRuntime: 	at com.facebook.marketing.internal.ButtonIndexer.add(Unknown Source)
>  E AndroidRuntime: 	at com.facebook.marketing.CodelessActivityLifecycleTracker$1.onActivityResumed(Unknown Source)
>  E AndroidRuntime: 	at android.app.Application.dispatchActivityResumed(Application.java:238)
>  E AndroidRuntime: 	at android.app.Activity.onResume(Activity.java:1372)
>  E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
>  E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6987)
>  E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)
>  E AndroidRuntime: 	... 10 more
>  I System.out: (HTTPLog)-Static: isSBSettingEnabled false
>  I System.out: (HTTPLog)-Static: isSBSettingEnabled false
>  W MTPRx   : notification from stack 3
>  E MTPRx   : in isSyncFinished posting message with delay of 4sec
>  W MTPRx   : notification from stack 10
>  D EnterpriseController: netId is 0
>  D Netd    : getNetworkForDns: using netid 502 for uid 10276
>  D SettingsProvider: isChangeAllowed() SettingsProvider : name = mtp_sync_alive
>  W MTPRx   : notification from stack 3
>  E MTPRx   : in isSyncFinished posting message with delay of 4sec
>  W ActivityManager:   Force finishing activity com.HIDDEN.HIDDEN/com.unity3d.player.UnityPlayerActivity

Here the only one post I found about this, with no response either:
https://forum.unity.com/threads/random-unable-to-resume-activity-window-couldnt-find-content-container-view.620545/

I assume that there's a mismatch between ID's somewhere in some views. Also, I read that disabling IAP logging through developer.facebook.com helps. And it helps, it crashes 50% of the times instead of 80%.

On Facebook SDK 7.13 everything works perfectly, that's why we're keeping that version, but Facebook now enforces installing the new one.

**Comment by zenith-jacob** [comment]
Two months ago, 10 SDK updates later, still no luck.
I've tried rewriting the entire Facebook SDK, still no luck.

The only option here is using 7.1.3, because it does not have these codeless shitty buggy scripts.
But it's using old libs like support-v4 from the native Android stack, so it's incompatible with AndroidX and the latest PlayServicesResolver.

**Comment by realluhui** [comment]
same issue in samsung device
using 7.17.2, the issue still exist

**Comment by 1901** [comment]
same issue

**Comment by edgarhit-git** [comment]
same issue

**Comment by 546342** [comment]
some issue

**Comment by maxim-wgames** [comment]
There are one pull request with fix for this bug: https://github.com/facebook/facebook-sdk-for-unity/pull/179
It turned off IAP logging. I just merge it with sdk v7.18 and build Facebook.Unity.dll

**Comment by artyom-kolesnikov** [comment]
We have a crash because of the same exception when user tries to log in with Facebook. I've reported a bug here: https://developers.facebook.com/support/bugs/2255632138073467/

**Comment by jgersindemir** [comment]
Same problem. We are receiving crashes from Android side (No problem on IOS ) . 
Unity v. :2018.4.22f1
Facebook SDK 7.19.2
