### ISSUE TITLE
facebook init error

### ISSUE THREAD

**Issue by JaeKyoungJeon** [facebook/facebook-sdk-for-unity#325]
Hi. using unity 2018.3.2.f1.
facebook sdk 7.17.2 version.

This error occurs when I run the Facebook example on the device and then click 'init' button.

2019-09-06 12:41:04.534 16779-16825/? E/Unity: AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='GetUserID' signature='()Ljava/lang/String;' in class Ljava.lang.Object;
    java.lang.NoSuchMethodError: no static method with name='GetUserID' signature='()Ljava/lang/String;' in class Ljava.lang.Object;
        at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:167)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:395)
        at android.os.Looper.loop(Looper.java:181)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidReflection.GetMethodM

i need help...

**Comment by yurfdog** [comment]
Check that you have the correct version of file:
`Assets/FacebookSDK/Plugins/Android/libs/facebook-android-wrapper-7.17.2.aar`

And no other version, such as facebook-android-wrapper-7.15.0.aar.
It looks like FB.GetUserID was added in 7.16.0.

**Comment by JaeKyoungJeon** [comment]
Thank you for answer.

My project has two versions 7.15, 7.17.2 in its path. Should I delete one of them ??

**Comment by KylinChang** [comment]
Hey @JaeKyoungJeon , I think the reason is you upgrading FB SDK without deleting the old SDK. I think you can delete the old SDK and then import the new one to fix the issue.

**Comment by JaeKyoungJeon** [comment]
Hi.

using version from the link : https://developers.facebook.com/docs/unity.

Assets \ FacebookSDK \ Plugins \ Android \ libs In this path,
facebook-android-wrapper-7.15.1 and facebook-android-wrapper-7.17.2 exist
simultaneously.

Please help T_T

2019년 9월 7일 (토) 오후 4:54, KylinChang <notifications@github.com>님이 작성:

**Comment by JaeKyoungJeon** [comment]
testfacebook.zip
<https://drive.google.com/file/d/1Y2dZmJ_M8uwQZYoUvbPlXVeCY5kSNNao/view?usp=drive_web>

this project... please help me T_T

2019년 9월 8일 (일) 오후 3:17, JaeKyoung Jeon <agewsj@gmail.com>님이 작성:

**Comment by JaeKyoungJeon** [comment]
This bug was fixed using Progard.

Thank you.
