### ISSUE TITLE
Error: Program type already present: android.support.customtabs.ICustomTabsCallback

### ISSUE THREAD

**Issue by yunlongHe** [facebook/facebook-sdk-for-unity#340]
unity 2018.3.0f2 and facebook sdk 7.18.0 
when i am build android apk i get this error:

Error: Program type already present: android.support.customtabs.ICustomTabsCallback

below is my dependencies in gradle file:
dependencies {
    // Your other dependencies //
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.android.gms:play-services-ads:18.2.0'
        implementation(name: 'android.arch.lifecycle.runtime-1.0.3', ext:'aar')
    implementation(name: 'audience-network-sdk-5.5.0', ext:'aar')
    implementation(name: 'com.android.support.animated-vector-drawable-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.appcompat-v7-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.cardview-v7-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.customtabs-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-compat-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-core-ui-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-core-utils-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-fragment-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-media-compat-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-v4-27.0.2', ext:'aar')
    implementation(name: 'com.android.support.support-vector-drawable-27.0.2', ext:'aar')
    implementation(name: 'com.facebook.android.facebook-applinks-5.8.0', ext:'aar')
    implementation(name: 'com.facebook.android.facebook-common-5.8.0', ext:'aar')
    implementation(name: 'com.facebook.android.facebook-core-5.8.0', ext:'aar')
    implementation(name: 'com.facebook.android.facebook-login-5.8.0', ext:'aar')
    implementation(name: 'com.facebook.android.facebook-share-5.8.0', ext:'aar')
    implementation(name: 'facebook-android-wrapper-7.18.0', ext:'aar')
    implementation(name: 'installreferrer-1.0', ext:'aar')
    implementation(name: 'recyclerview-v7-25.3.1', ext:'aar')
    implementation project(':IronSource')
    implementation project(':unity-android-resources')

     // Your other dependencies //
     // ... //
     // AdMob's dependency //
     // implementation 'com.google.android.gms:play-services-ads:18.2.0'
}

when i comment out 
// implementation(name: 'com.android.support.customtabs-27.0.2', ext:'aar')

the error vanish but i still get an error
Program type already present: android.support.v4.os.ResultReceiver

and i comment out another dependency
// implementation(name: 'com.android.support.support-compat-27.0.2', ext:'aar')

the build can run successfully, but when i call FB.LogInWithReadPermissions, tha app crashes and a fatal exception is thrown:

2019-10-17 21:02:39.922 12040-12040/com.mirrortech.tankwar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mirrortech.tankwar, PID: 12040
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90)
        at com.facebook.unity.FBLogin.login(FBLogin.java:125)
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43)
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.FragmentActivity
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/BaseFragmentActivityApi16;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.BaseFragmentActivityApi16
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/BaseFragmentActivityApi14;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.BaseFragmentActivityApi14
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/SupportActivity;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
2019-10-17 21:02:40.154 12040-12099/com.mirrortech.tankwar E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '557839314985787' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
2019-10-17 21:02:43.046 12040-12040/com.mirrortech.tankwar E/CrashReport: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90)
        at com.facebook.unity.FBLogin.login(FBLogin.java:125)
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43)
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.FragmentActivity
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/BaseFragmentActivityApi16;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.BaseFragmentActivityApi16
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/BaseFragmentActivityApi14;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.BaseFragmentActivityApi14
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/SupportActivity;
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:90) 
        at com.facebook.unity.FBLogin.login(FBLogin.java:125) 
        at com.facebook.unity.FBLogin.loginWithReadPermissions(FBLogin.java:43) 
        at com.facebook.unity.FBUnityLoginActivity.onCreate(FBUnityLoginActivity.java:40) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.SupportActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/base.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_resources_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0zIendg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.mirrortech.tankwar-I9N7ZhtvIifHe6N0

**Comment by KylinChang** [comment]
Hi @yunlongHe , from the stacktrace `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;`, I think the reason is class FragmentActivity not compiled with your app and you can solve the issue by adding `keepclass` rule to your Proguard file

**Comment by yinjimmy** [comment]
## edit `gradle.properties`

```
android.useAndroidX=true
android.enableJetifier=true

# Android SDK version that will be used as the compile project
PROP_COMPILE_SDK_VERSION=28

# Android SDK version that will be used as the earliest version of android this application can run on
PROP_MIN_SDK_VERSION=16

# Android SDK version that will be used as the latest version of android this application has been tested on
PROP_TARGET_SDK_VERSION=28
```

https://discuss.cocos2d-x.org/t/fail-to-compile/49513/3?u=yinjimmy
