### ISSUE TITLE
Android:ShareLink Crash

### ISSUE THREAD

**Issue by Surc** [facebook/facebook-sdk-for-unity#427]
## Environment
Unity Version: 2018.4.36
Facebook Unity SDK : 7.18.1

has installed Facebook app but never started

## Expected Results

What do you expect to happen?

## Actual Results
 sharedLink success

What actually happened? Can you provide a stack trace?
app crash

## Steps to Reproduce
Installed Facebook app but never started,
start My App , use ShareLink

The  error:

## Environment
Unity Version: 2018.4.36
Facebook Unity SDK : 7.18.1

has installed Facebook app but never started

## Expected Results

What do you expect to happen?

## Actual Results
 sharedLink success

What actually happened? Can you provide a stack trace?
app crash

## Steps to Reproduce
Installed Facebook app but never started,
start My App , use ShareLink

The  error:
04-08 20:46:44.028 14054-14091/? V/com.facebook.unity.FB: ShareLink({"content_url":"http://192.168.1.100/share/facebook/c5f7a030-7961-11ea-9e9a-c9e2e65b4345.html"})
04-08 20:46:44.035 1209-2275/? I/ActivityManager: START u0 {cmp=com.xd.box/com.facebook.unity.FBUnityDialogsActivity (has extras)} from uid 10226 from pid 14054 on display 0
04-08 20:46:44.045 1209-2275/? V/WindowManager: Set focused app to: AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}} old focus=AppWindowToken{55cee9f token=Token{a80ca66 ActivityRecord{2c922c1 u0 com.xd.box/.MainActivity t77073}}} moveFocusNow=true
04-08 20:46:44.046 1209-2275/? V/WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}}
04-08 20:46:44.104 14054-14054/? V/ActivityThread: Handling launch of ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}} startsNotResumed=false
04-08 20:46:44.104 14054-14054/? V/ActivityThread: ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}}: app=android.app.Application@f0eb74e, appName=com.xd.box, pkg=com.xd.box, comp={com.xd.box/com.facebook.unity.FBUnityDialogsActivity}, dir=/data/app/com.xd.box-1/base.apk
04-08 20:46:44.111 14054-14088/? I/ContentCatcher: Interceptor : Catcher list invalid for com.xd.box@com.facebook.unity.FBUnityDialogsActivity@12255214
04-08 20:46:44.126 1209-1262/? V/WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}}
04-08 20:46:44.133 1209-1262/? V/WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}}
04-08 20:46:44.135 1209-1262/? V/WindowManager: Set focused app to: AppWindowToken{49a632f token=Token{563ed0e ActivityRecord{a9e0709 u0 com.xd.box/com.facebook.FacebookActivity t77073}}} old focus=AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}} moveFocusNow=true
04-08 20:46:44.137 14054-14054/? V/ActivityThread: Performing resume of ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}}
04-08 20:46:44.137 14054-14054/? V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.facebook.unity.FBUnityDialogsActivity  onActivityResumed
04-08 20:46:44.140 14054-14054/? D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}}
04-08 20:46:44.140 14054-14054/? V/ActivityThread: Resume ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}} started activity: true, hideForNow: false, finished: false
04-08 20:46:44.145 14054-14054/? D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{9948ca1 com.xd.box/com.facebook.unity.FBUnityDialogsActivity,ident = 2}
04-08 20:46:44.147 1209-2295/? D/WindowManager: addWindowToListInOrderLocked: win=Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity} Callers=com.android.server.wm.WindowManagerService.addWindow:2797 com.android.server.wm.Session.addToDisplay:181 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:143 
04-08 20:46:44.150 14054-14054/? V/ActivityThread: Resuming ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}} with isForward=true
04-08 20:46:44.150 14054-14054/? V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{9948ca1 com.xd.box/com.facebook.unity.FBUnityDialogsActivity,ident = 2}, this =com.android.internal.policy.PhoneWindow$DecorView{663e325 V.E...... R.....I. 0,0-0,0}
04-08 20:46:44.150 14054-14054/? V/ActivityThread: Scheduling idle handler for ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}}
04-08 20:46:44.168 357-357/? I/BufferQueueConsumer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:0,p:-1,c:357) setConsumerName: com.xd.box/com.facebook.unity.FBUnityDialogsActivity
04-08 20:46:44.168 357-357/? I/BufferQueueConsumer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:0,p:-1,c:357) setDefaultBufferSize: width=1080 height=1920
04-08 20:46:44.174 14054-14230/? D/OpenGLRenderer: CanvasContext() 0xcc06d000 initialize window=0xcf202e08, title=com.xd.box/com.facebook.unity.FBUnityDialogsActivity
04-08 20:46:44.174 357-400/? I/BufferQueueProducer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:14054,c:357) connect(P): api=1 producer=(14054:com.xd.box) producerControlledByApp=true
04-08 20:46:44.184 357-1534/? D/BufferQueueProducer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:14054,c:357) allocateBuffers: allocating from 4 buffers up to 4 buffers
04-08 20:46:44.185 14054-14054/? V/MicroMsg.SDK.WXApiImplV10.ActivityLifecycleCb: com.facebook.unity.FBUnityDialogsActivity  onActivityPaused
04-08 20:46:44.185 14054-14054/? D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{6a94033 token=android.os.BinderProxy@2120ff0 {com.xd.box/com.facebook.unity.FBUnityDialogsActivity}}
04-08 20:46:44.197 357-456/? I/BufferQueueProducer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:14054,c:357) new GraphicBuffer needed
04-08 20:46:44.203 357-1534/? I/BufferQueueProducer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:14054,c:357) new GraphicBuffer needed
04-08 20:46:44.232 14054-14054/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xd.box, PID: 14054
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2017.4.36f1
    Device model      : Xiaomi Redmi Note 4
    Device fingerprint: Xiaomi/nikel/nikel:6.0/MRA58K/V10.2.2.0.MBFCNXM:user/release-keys
    
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/core/internal/FastSafeIterableMap;
        at android.arch.lifecycle.LifecycleRegistry.<init>(LifecycleRegistry.java:59)
        at android.support.v4.app.SupportActivity.<init>(SupportActivity.java:47)
        at android.support.v4.app.BaseFragmentActivityApi14.<init>(BaseFragmentActivityApi14.java:28)
        at android.support.v4.app.BaseFragmentActivityApi16.<init>(BaseFragmentActivityApi16.java:34)
        at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:67)
        at com.facebook.FacebookActivity.<init>(FacebookActivity.java:53)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1072)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670)
        at android.app.ActivityThread.access$1100(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.core.internal.FastSafeIterableMap" on path: DexPathList[[zip file "/data/app/com.xd.box-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xd.box-1/lib/arm, /data/app/com.xd.box-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.arch.lifecycle.LifecycleRegistry.<init>(LifecycleRegistry.java:59) 
        at android.support.v4.app.SupportActivity.<init>(SupportActivity.java:47) 
        at android.support.v4.app.BaseFragmentActivityApi14.<init>(BaseFragmentActivityApi14.java:28) 
        at android.support.v4.app.BaseFragmentActivityApi16.<init>(BaseFragmentActivityApi16.java:34) 
        at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:67) 
        at com.facebook.FacebookActivity.<init>(FacebookActivity.java:53) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1072) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
    	Suppressed: java.lang.ClassNotFoundException: android.arch.core.internal.FastSafeIterableMap
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 19 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-08 20:46:44.238 1209-2317/? V/WindowManager: Set focused app to: AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}} old focus=AppWindowToken{49a632f token=Token{563ed0e ActivityRecord{a9e0709 u0 com.xd.box/com.facebook.FacebookActivity t77073}}} moveFocusNow=true
04-08 20:46:44.239 1209-2317/? V/WindowManager: findFocusedWindow: Found new focus @ 14 = Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.239 1209-2317/? V/WindowManager: Changing focus from null to Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity} Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4515 com.android.server.am.ActivityManagerService.setFocusedActivityLocked:3056 com.android.server.am.ActivityStack.adjustFocusedActivityLocked:3070 com.android.server.am.ActivityStack.finishActivityLocked:3360 
04-08 20:46:44.240 1209-2317/? D/WindowManager: Input focus has changed to Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.240 1209-1253/? I/WindowManager: Focus moving from null to Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.240 1209-1253/? I/WindowManager: Gaining focus: Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.241 1209-2317/? W/ActivityManager:   Force finishing activity com.xd.box/com.facebook.unity.FBUnityDialogsActivity
04-08 20:46:44.241 1209-2317/? V/WindowManager: findFocusedWindow: Found new focus @ 14 = Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.243 1209-2317/? V/WindowManager: Set focused app to: AppWindowToken{55cee9f token=Token{a80ca66 ActivityRecord{2c922c1 u0 com.xd.box/.MainActivity t77073}}} old focus=AppWindowToken{c6b010 token=Token{fd626c2 ActivityRecord{fbb070d u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity t77073}}} moveFocusNow=true
04-08 20:46:44.243 1209-2317/? V/WindowManager: findFocusedWindow: Found new focus @ 14 = Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.430 1209-2275/? I/WindowState: WIN DEATH: Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity}
04-08 20:46:44.430 1209-2275/? V/WindowManager: Remove Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity} client=54ebd3c, surface=Surface(name=com.xd.box/com.facebook.unity.FBUnityDialogsActivity) Callers=com.android.server.wm.WindowState$DeathRecipient.binderDied:1251 android.os.BinderProxy.sendDeathNotice:570 <bottom of call stack> <bottom of call stack> 
04-08 20:46:44.433 1209-2275/? V/WindowManager: Changing focus from Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity EXITING} to Window{f541c84 u0 com.xd.box/com.xd.box.MainActivity} Callers=com.android.server.wm.WindowManagerService.removeWindowLocked:3002 com.android.server.wm.WindowState$DeathRecipient.binderDied:1251 android.os.BinderProxy.sendDeathNotice:570 <bottom of call stack> 
04-08 20:46:44.437 357-400/? I/BufferQueueProducer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:-1,c:357) disconnect(P): api 1
04-08 20:46:44.438 357-400/? I/BufferQueueConsumer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:-1,c:357) getReleasedBuffers: returning mask 0xffffffffffffffff
04-08 20:46:44.449 1209-1253/? I/WindowManager: Focus moving from Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity EXITING} to null
04-08 20:46:44.449 1209-1253/? I/WindowManager: Losing focus: Window{8970ac5 u0 com.xd.box/com.facebook.unity.FBUnityDialogsActivity EXITING}
04-08 20:46:44.855 357-456/? D/SurfaceFlinger:     remove: com.xd.box/com.facebook.unity.FBUnityDialogsActivity
04-08 20:46:44.867 357-357/? I/BufferQueueConsumer: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:-1,c:-1) disconnect(C)
04-08 20:46:44.867 357-357/? I/BufferQueue: [com.xd.box/com.facebook.unity.FBUnityDialogsActivity](this:0x7f89469800,id:2207,api:1,p:-1,c:-1) ~BufferQueueCore

**Comment by Surc** [comment]
Solved it ,Unity->Assets->Play Service Resolver ->Android Resolver -> Force Resolver  ~
