### ISSUE TITLE
Unity FB.AppRequest call crash on Android

### ISSUE THREAD

**Issue by jck9906** [facebook/facebook-sdk-for-unity#558]
Unity version : 2020.1.2f1
FB SDK version : 9.2.0

The app is a copy app of the original app that has already been released.

This is my code:
FB.AppRequest("Test Message", callback: this.HandleResult);

This is error log
AndroidRuntime java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxx.xxxxxx/com.facebook.unity.FBUnityGameRequestActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Please help me...

+
FB.LogInWithReadPermissions(new List<string>() { "public_profile", "email", "user_friends" }, HandleLogin);
If I don't call login API, it doesn't crash. but call login(and login success)  then make crash. 

A crash occurs when calling FB.AppRequest while logged in, and no crash occurs when calling FB.AppRequest when not logged in.
...

**Comment by paradizIscool** [comment]
Hi, Same issue, how did you fix that?

**Comment by sandolkakos** [comment]
We have exactly the same issue in our project.

Unity version : 2020.3.16f1
FB for Unity SDK version : 11.0.0

I found a similar issue on the repo of the Facebook Android SDK, where they think it was fixed on the SDK version 12.1.0:
- https://github.com/facebook/facebook-android-sdk/issues/906

Any idea about when the plugin for Unity will get updated? (the last update was in June 2021)
