### ISSUE TITLE
Cause application crash and flash back.Reason:Window couldn't find content container view

### ISSUE THREAD

**Issue by ye503837526** [facebook/facebook-sdk-for-unity#636]
FaceBook SDK Version: 13.2.0
Unity version       : 2019.4.26f1
Device model      : OPPO OPPO A37f...
Android Version : 5,6

Problem description:  Crash when using Facebook to pull up login and close authorized login page .Multiple devices

Error information:
Caused by: java.lang.RuntimeException: Window couldn't find content container view
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3882)
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3960)
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2070)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3384)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2683)
        at android.app.ActivityThread.access$900(ActivityThread.java:187)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:5809)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

The crash occurred in facebook11.0. After I upgraded from facebook11.0 to 13.2.0, it still crashed and remained unresolved. I have analyzed the log for a long time, but I don't know how to solve it, because the error is in the Android layer.

**Comment by Prakhar-kuls** [comment]
@ye503837526 found something on this?
