### ISSUE TITLE
Exception: Too many receivers, total of 1000

### ISSUE THREAD

**Issue by evgeny-detkov** [facebook/facebook-sdk-for-unity#706]
## Environment

- Unity Editor Version: `2020.3.48f1`
- Unity SDK Version: `16.0.2`
- Installation Platform & Verison: `Android 12-13`

## Actual Results / Steps to Reproduce

In the Crashlytics service, we have been receiving the same error from players for about 3 months. Judging by the report, the exception only occurs on Samsung devices running Android 12/13. We cannot reproduce this ourselves.

The error looks like this:

```
Caused by java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2885, callerPackage: com.excelliance.multiaccount
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3031)
       at android.os.Parcel.createException(Parcel.java:3007)
       at android.os.Parcel.readException(Parcel.java:2990)
       at android.os.Parcel.readException(Parcel.java:2932)
       at com.excelliance.kxqp.platform.a.i.a()
       at com.excelliance.kxqp.platform.c.i.a()
       at com.excelliance.kxqp.platform.c.b.e.bq.b()
       at com.excelliance.kxqp.platform.c.b.f.a()
       at com.excelliance.kxqp.platform.c.b.a.a.invoke()
       at com.excelliance.kxqp.platform.c.b.a.c.invoke()
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy8.getContentProvider()
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:7915)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3665)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
       at android.content.ContentResolver.query(ContentResolver.java:1210)
       at android.content.ContentResolver.query(ContentResolver.java:1158)
       at android.content.ContentResolver.query(ContentResolver.java:1114)
       at com.facebook.internal.NativeProtocol.fetchAllAvailableProtocolVersionsForAppInfo(NativeProtocol.kt:10)
       at com.facebook.internal.NativeProtocol.access$fetchAllAvailableProtocolVersionsForAppInfo(NativeProtocol.kt:1)
       at com.facebook.internal.NativeProtocol$NativeAppInfo.fetchAvailableVersions(NativeProtocol.kt:2)
       at com.facebook.internal.NativeProtocol.updateAllAvailableProtocolVersionsAsync$lambda-1(NativeProtocol.kt:2)
       at com.facebook.internal.NativeProtocol.a()
       at com.facebook.internal.p.run()
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

I can’t provide all the integration code, but we integrated according to the example from the documentation. Facebook SDK has been integrated for 3 years already, we try to update it quite often. At the beginning of the year we did not notice such a problem.

Can you help?

**Comment by evgeny-detkov** [comment]
up
